const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{"8Directions": 0},
	{DéfilerVers: 0},
	{Soldat1: 0},
	{Clavier: 0},
	{Question: 0},
	{Souris: 0},
	{Choix1: 0},
	{Choix2: 0},
	{Choix3: 0},
	{BGGameOver: 0},
	{GameOvertxt: 0},
	{RESTARTtxt: 0},
	{BGGGWP: 0},
	{YOUWONtxt: 0},
	{Back2Battletxt: 0},
	{Soldat2: 0},
	{ArrièreplanRépété: 0},
	{Solide: 0},
	{Sandbag: 0},
	{DesertedTraitor: 0},
	{Back2Battlefield2: 0},
	{BarbedWires: 0},
	{Sprite2: 0},
	{Yourededtxt: 0},
	{barbedwiretxt: 0},
	{tryagaintxt: 0},
	{Sprite: 0}
];

self.InstanceType = {
	Soldat1: class extends self.ISpriteInstance {},
	Clavier: class extends self.IInstance {},
	Question: class extends self.ITextInstance {},
	Souris: class extends self.IInstance {},
	Choix1: class extends self.ITextInstance {},
	Choix2: class extends self.ITextInstance {},
	Choix3: class extends self.ITextInstance {},
	BGGameOver: class extends self.ISpriteInstance {},
	GameOvertxt: class extends self.ITextInstance {},
	RESTARTtxt: class extends self.ITextInstance {},
	BGGGWP: class extends self.ISpriteInstance {},
	YOUWONtxt: class extends self.ITextInstance {},
	Back2Battletxt: class extends self.ITextInstance {},
	Soldat2: class extends self.ISpriteInstance {},
	ArrièreplanRépété: class extends self.ITiledBackgroundInstance {},
	Sandbag: class extends self.ISpriteInstance {},
	DesertedTraitor: class extends self.ITextInstance {},
	Back2Battlefield2: class extends self.ITextInstance {},
	BarbedWires: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Yourededtxt: class extends self.ITextInstance {},
	barbedwiretxt: class extends self.ITextInstance {},
	tryagaintxt: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {}
}